[package]
name = "axvisor-linux-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib"]

[features]
default = []
control = ["axvisor_api/control"]
shell = ["axvisor_api/shell"]

[dependencies]
axvisor_api = { git = "https://github.com/numpy1314/tgoskits", rev = "78c84a4349649be2f7cb39328e0e3293a959a04d", default-features = false }
ax-errno = { git = "https://github.com/numpy1314/tgoskits", rev = "78c84a4349649be2f7cb39328e0e3293a959a04d" }
spin = "0.12"
