[package]
name = "axvisor-linux-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib"]

[features]
default = []
control = ["axvisor_api/control"]
arm-vhe = ["axvisor_api/arm-vhe"]
shell = ["axvisor_api/shell"]

[dependencies]
axvisor_api = { git = "https://github.com/numpy1314/tgoskits", rev = "a02309312efcc229f9891e0f73c45422d442f7fc", default-features = false }
ax-errno = { git = "https://github.com/numpy1314/tgoskits", rev = "a02309312efcc229f9891e0f73c45422d442f7fc" }
spin = "0.12"
