[package]
name = "axvisor-linux-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib"]

[features]
default = []
control = ["axvisor_api/control", "axvisor_core/control"]
shell = ["axvisor_api/shell", "axvisor_core/shell"]
sstc = ["axvisor_core/sstc"]
svm = ["axvisor_core/svm"]
vmx = ["axvisor_core/vmx"]
conformance-test = ["dep:axvisor-linux-conformance"]

[dependencies]
axvisor_core = { git = "https://github.com/numpy1314/tgoskits", rev = "78c84a4349649be2f7cb39328e0e3293a959a04d", default-features = false }
axvisor_api = { git = "https://github.com/numpy1314/tgoskits", rev = "78c84a4349649be2f7cb39328e0e3293a959a04d", default-features = false }
axvisor-linux-conformance = { path = "../axvisor-linux-conformance", optional = true }
ax-percpu = { git = "https://github.com/numpy1314/tgoskits", rev = "78c84a4349649be2f7cb39328e0e3293a959a04d", features = ["custom-base", "external-base"] }
log = "0.4"
